version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      # - OLLAMA_ORIGINS=http://0.0.0.0:11434
  
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ollama
  
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    volumes:
      - ./app:/app
    environment:
      - OLLAMA_HOST=http://proxy:80
    depends_on:
      - proxy
  
volumes:
  ollama: 