version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434


  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "1024:1024"
    depends_on:
      - ollama
      - chroma
  
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_index:/chroma/.chroma/index
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
  
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    volumes:
      - ./app:/app
    environment:
      - OLLAMA_HOST=http://proxy:1024
    depends_on:
      - proxy
  
volumes:
  ollama:
  chroma_index: