version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "11434:11434" 